// src/constants/cities.ts

export interface IlModel {
    id: number;
    isim: string;
    plaka: string;
    ilceler: string[];
}

export const iller: IlModel[] = [
    { id: 1, isim: "Adana", plaka: "01", ilceler: ["Seyhan", "Yüreğir", "Çukurova", "Sarıçam", "Ceyhan", "Kozan", "İmamoğlu", "Karataş", "Karaisalı", "Pozantı", "Yumurtalık", "Tufanbeyli", "Feke", "Aladağ", "Saimbeyli"] },
    { id: 2, isim: "Adıyaman", plaka: "02", ilceler: ["Merkez", "Kahta", "Besni", "Gölbaşı", "Gerger", "Sincik", "Çelikhan", "Tut", "Samsat"] },
    { id: 3, isim: "Afyonkarahisar", plaka: "03", ilceler: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Sinanpaşa", "Emirdağ", "Şuhut", "Çay", "İhsaniye", "İscehisar", "Sultandağı", "Çobanlar", "Dazkırı", "Başmakçı", "Hocalar", "Bayat", "Evciler", "Kızılören"] },
    { id: 4, isim: "Ağrı", plaka: "04", ilceler: ["Merkez", "Patnos", "Doğubayazıt", "Diyadin", "Eleşkirt", "Tutak", "Taşlıçay", "Hamur"] },
    { id: 5, isim: "Amasya", plaka: "05", ilceler: ["Merkez", "Merzifon", "Suluova", "Taşova", "Gümüşhacıköy", "Göynücek", "Hamamözü"] },
    { id: 6, isim: "Ankara", plaka: "06", ilceler: ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı", "Polatlı", "Çubuk", "Kahramankazan", "Beypazarı", "Elmadağ", "Şereflikoçhisar", "Akyurt", "Nallıhan", "Haymana", "Kızılcahamam", "Bala", "Kalecik", "Ayaş", "Güdül", "Çamlıdere", "Evren"] },
    { id: 7, isim: "Antalya", plaka: "07", ilceler: ["Kepez", "Muratpaşa", "Alanya", "Manavgat", "Konyaaltı", "Serik", "Aksu", "Döşemealtı", "Kumluca", "Kaş", "Korkuteli", "Gazipaşa", "Finike", "Kemer", "Elmalı", "Demre", "Akseki", "Gündoğmuş", "İbradı"] },
    { id: 8, isim: "Artvin", plaka: "08", ilceler: ["Merkez", "Hopa", "Borçka", "Arhavi", "Yusufeli", "Şavşat", "Ardanuç", "Murgul", "Kemalpaşa"] },
    { id: 9, isim: "Aydın", plaka: "09", ilceler: ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "İncirliova", "Çine", "Germencik", "Bozdoğan", "Köşk", "Kuyucak", "Sultanhisar", "Karacasu", "Yenipazar", "Buharkent", "Karpuzlu"] },
    { id: 10, isim: "Balıkesir", plaka: "10", ilceler: ["Altıeylül", "Karesi", "Edremit", "Bandırma", "Gönen", "Ayvalık", "Burhaniye", "Bigadiç", "Susurluk", "Dursunbey", "Sındırgı", "İvrindi", "Erdek", "Havran", "Kepsut", "Manyas", "Savaştepe", "Balya", "Gömeç", "Marmara"] },
    { id: 11, isim: "Bilecik", plaka: "11", ilceler: ["Merkez", "Bozüyük", "Osmaneli", "Söğüt", "Gölpazarı", "Pazaryeri", "İnhisar", "Yenipazar"] },
    { id: 12, isim: "Bingöl", plaka: "12", ilceler: ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yedisu", "Yayladere"] },
    { id: 13, isim: "Bitlis", plaka: "13", ilceler: ["Tatvan", "Merkez", "Güroymak", "Ahlat", "Hizan", "Mutki", "Adilcevaz"] },
    { id: 14, isim: "Bolu", plaka: "14", ilceler: ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen", "Yeniçağa", "Dörtdivan", "Seben", "Kıbrıscık"] },
    { id: 15, isim: "Burdur", plaka: "15", ilceler: ["Merkez", "Bucak", "Gölhisar", "Yeşilova", "Çavdır", "Tefenni", "Karamanlı", "Ağlasun", "Altınyayla", "Çeltikçi", "Kemer"] },
    { id: 16, isim: "Bursa", plaka: "16", ilceler: ["Osmangazi", "Yıldırım", "Nilüfer", "İnegöl", "Gemlik", "Mustafakemalpaşa", "Mudanya", "Gürsu", "Karacabey", "Orhangazi", "Kestel", "Yenişehir", "İznik", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"] },
    { id: 17, isim: "Çanakkale", plaka: "17", ilceler: ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık", "Yenice", "Ezine", "Bayramiç", "Lapseki", "Eceabat", "Gökçeada", "Bozcaada"] },
    { id: 18, isim: "Çankırı", plaka: "18", ilceler: ["Merkez", "Çerkeş", "Ilgaz", "Orta", "Şabanözü", "Kurşunlu", "Yapraklı", "Kızılırmak", "Atkaracalar", "Eldivan", "Korgun", "Bayramören"] },
    { id: 19, isim: "Çorum", plaka: "19", ilceler: ["Merkez", "Sungurlu", "Osmancık", "İskilip", "Alaca", "Bayat", "Kargı", "Mecitözü", "Ortaköy", "Uğurludağ", "Dodurga", "Oğuzlar", "Laçin", "Boğazkale"] },
    { id: 20, isim: "Denizli", plaka: "20", ilceler: ["Pamukkale", "Merkezefendi", "Çivril", "Acıpayam", "Tavas", "Honaz", "Sarayköy", "Buldan", "Kale", "Çal", "Çameli", "Serinhisar", "Bozkurt", "Güney", "Çardak", "Bekilli", "Beyağaç", "Babadağ", "Baklan"] },
    { id: 21, isim: "Diyarbakır", plaka: "21", ilceler: ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Ergani", "Bismil", "Silvan", "Çınar", "Çermik", "Dicle", "Kulp", "Hani", "Lice", "Eğil", "Hazro", "Kocaköy", "Çüngüş"] },
    { id: 22, isim: "Edirne", plaka: "22", ilceler: ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Meriç", "Enez", "Süloğlu", "Lalapaşa"] },
    { id: 23, isim: "Elazığ", plaka: "23", ilceler: ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Baskil", "Arıcak", "Maden", "Sivrice", "Alacakaya", "Keban", "Ağın"] },
    { id: 24, isim: "Erzincan", plaka: "24", ilceler: ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "İliç", "Kemah", "Kemaliye", "Otlukbeli", "Refahiye"] },
    { id: 25, isim: "Erzurum", plaka: "25", ilceler: ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Oltu", "Pasinler", "Karayazı", "Hınıs", "Tekman", "Karaçoban", "Aşkale", "Şenkaya", "Çat", "Köprüköy", "İspir", "Tortum", "Narman", "Uzundere", "Olur", "Pazaryolu"] },
    { id: 26, isim: "Eskişehir", plaka: "26", ilceler: ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler", "Seyitgazi", "Alpu", "Mihalıççık", "Mahmudiye", "Beylikova", "İnönü", "Günyüzü", "Han", "Sarıcakaya", "Mihalgazi"] },
    { id: 27, isim: "Gaziantep", plaka: "27", ilceler: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Araban", "Oğuzeli", "Yavuzeli", "Karkamış"] },
    { id: 28, isim: "Giresun", plaka: "28", ilceler: ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Dereli", "Şebinkarahisar", "Keşap", "Yağlıdere", "Piraziz", "Eynesil", "Alucra", "Çamoluk", "Güce", "Doğankent", "Çanakçı"] },
    { id: 29, isim: "Gümüşhane", plaka: "29", ilceler: ["Merkez", "Kelkit", "Şiran", "Kürtün", "Torul", "Köse"] },
    { id: 30, isim: "Hakkari", plaka: "30", ilceler: ["Yüksekova", "Merkez", "Şemdinli", "Çukurca", "Derecik"] },
    { id: 31, isim: "Hatay", plaka: "31", ilceler: ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı", "Arsuz", "Altınözü", "Hassa", "Payas", "Erzin", "Yayladağı", "Belen", "Kumlu"] },
    { id: 32, isim: "Isparta", plaka: "32", ilceler: ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Keçiborlu", "Senirkent", "Sütçüler", "Gönen", "Uluborlu", "Atabey", "Aksu", "Yenişarbademli"] },
    { id: 33, isim: "Mersin", plaka: "33", ilceler: ["Tarsus", "Toroslar", "Yenişehir", "Akdeniz", "Mezitli", "Erdemli", "Silifke", "Anamur", "Mut", "Bozyazı", "Gülnar", "Aydıncık", "Çamlıyayla"] },
    { id: 34, isim: "İstanbul", plaka: "34", ilceler: ["Esenyurt", "Küçükçekmece", "Bağcılar", "Pendik", "Ümraniye", "Bahçelievler", "Sultangazi", "Üsküdar", "Maltepe", "Gaziosmanpaşa", "Kadıköy", "Kartal", "Başakşehir", "Esenler", "Avcılar", "Kağıthane", "Fatih", "Sancaktepe", "Ataşehir", "Eyüpsultan", "Beylikdüzü", "Sarıyer", "Sultanbeyli", "Zeytinburnu", "Güngören", "Arnavutköy", "Şişli", "Bayrampaşa", "Tuzla", "Büyükçekmece", "Çekmeköy", "Beyoğlu", "Beykoz", "Bakırköy", "Silivri", "Beşiktaş", "Çatalca", "Şile", "Adalar"] },
    { id: 35, isim: "İzmir", plaka: "35", ilceler: ["Buca", "Karabağlar", "Bornova", "Konak", "Karşıyaka", "Bayraklı", "Çiğli", "Torbalı", "Menemen", "Gaziemir", "Ödemiş", "Kemalpaşa", "Bergama", "Aliağa", "Menderes", "Tire", "Balçova", "Narlıdere", "Urla", "Kiraz", "Dikili", "Bayındır", "Seferihisar", "Selçuk", "Güzelbahçe", "Foça", "Kınık", "Beydağ", "Karaburun"] },
    { id: 36, isim: "Kars", plaka: "36", ilceler: ["Merkez", "Kağızman", "Sarıkamış", "Selim", "Digor", "Arpaçay", "Akyaka", "Susuz"] },
    { id: 37, isim: "Kastamonu", plaka: "37", ilceler: ["Merkez", "Tosya", "Taşköprü", "Cide", "İnebolu", "Araç", "Devrekani", "Bozkurt", "Daday", "Azdavay", "Çatalzeytin", "Küre", "Doğanyurt", "İhsangazi", "Pınarbaşı", "Şenpazar", "Abana", "Seydiler", "Hanönü", "Ağlı"] },
    { id: 38, isim: "Kayseri", plaka: "38", ilceler: ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan", "İncesu", "Pınarbaşı", "Tomarza", "Yeşilhisar", "Sarıoğlan", "Hacılar", "Sarız", "Akkışla", "Felahiye", "Özvatan"] },
    { id: 39, isim: "Kırklareli", plaka: "39", ilceler: ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Pehlivanköy", "Kofçaz"] },
    { id: 40, isim: "Kırşehir", plaka: "40", ilceler: ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Boztepe", "Akçakent"] },
    { id: 41, isim: "Kocaeli", plaka: "41", ilceler: ["Gebze", "İzmit", "Darıca", "Körfez", "Gölcük", "Derince", "Çayırova", "Kartepe", "Başiskele", "Karamürsel", "Kandıra", "Dilovası"] },
    { id: 42, isim: "Konya", plaka: "42", ilceler: ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Çumra", "Seydişehir", "Ilgın", "Cihanbeyli", "Kulu", "Karapınar", "Kadınhanı", "Sarayönü", "Bozkır", "Yunak", "Doğanhisar", "Hüyük", "Altınekin", "Hadim", "Çeltik", "Emirgazi", "Tuzlukçu", "Derebucak", "Akören", "Halkapınar", "Yalıhüyük", "Taşkent", "Güneysınır", "Ahırlı", "Derbent"] },
    { id: 43, isim: "Kütahya", plaka: "43", ilceler: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Altıntaş", "Domaniç", "Hisarcık", "Aslanapa", "Çavdarhisar", "Şaphane", "Pazarlar", "Dumlupınar"] },
    { id: 44, isim: "Malatya", plaka: "44", ilceler: ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Pütürge", "Yazıhan", "Arapgir", "Arguvan", "Kuluncak", "Kale", "Doğanyol"] },
    { id: 45, isim: "Manisa", plaka: "45", ilceler: ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Saruhanlı", "Kula", "Kırkağaç", "Demirci", "Sarıgöl", "Gördes", "Selendi", "Ahmetli", "Gölmarmara", "Köprübaşı"] },
    { id: 46, isim: "Kahramanmaraş", plaka: "46", ilceler: ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Türkoğlu", "Pazarcık", "Göksun", "Andırın", "Çağlayancerit", "Nurhak", "Ekinözü"] },
    { id: 47, isim: "Mardin", plaka: "47", ilceler: ["Kızıltepe", "Artuklu", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Dargeçit", "Savur", "Yeşilli", "Ömerli"] },
    { id: 48, isim: "Muğla", plaka: "48", ilceler: ["Bodrum", "Fethiye", "Milas", "Menteşe", "Marmaris", "Seydikemer", "Ortaca", "Yatağan", "Dalaman", "Köyceğiz", "Ula", "Datça", "Kavaklıdere"] },
    { id: 49, isim: "Muş", plaka: "49", ilceler: ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"] },
    { id: 50, isim: "Nevşehir", plaka: "50", ilceler: ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Derinkuyu", "Acıgöl", "Kozaklı", "Hacıbektaş"] },
    { id: 51, isim: "Niğde", plaka: "51", ilceler: ["Merkez", "Bor", "Çiftlik", "Ulukışla", "Altunhisar", "Çamardı"] },
    { id: 52, isim: "Ordu", plaka: "52", ilceler: ["Altınordu", "Ünye", "Fatsa", "Erbaa", "Kumru", "Korgan", "Gölköy", "Ulubey", "Mesudiye", "Aybastı", "İkizce", "Gürgentepe", "Çatalpınar", "Çaybaşı", "Akkuş", "Kabataş", "Perşembe", "Kabadüz", "Çamaş", "Gülyalı"] },
    { id: 53, isim: "Rize", plaka: "53", ilceler: ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Fındıklı", "Güneysu", "Kalkandere", "İyidere", "Derepazarı", "Çamlıhemşin", "İkizdere", "Hemşin"] },
    { id: 54, isim: "Sakarya", plaka: "54", ilceler: ["Adapazarı", "Serdivan", "Akyazı", "Erenler", "Hendek", "Karasu", "Geyve", "Arifiye", "Sapanca", "Pamukova", "Ferizli", "Kaynarca", "Kocaali", "Söğütlü", "Karapürçek", "Taraklı"] },
    { id: 55, isim: "Samsun", plaka: "55", ilceler: ["İlkadım", "Atakum", "Bafra", "Çarşamba", "Canik", "Vezirköprü", "Terme", "Tekkeköy", "Havza", "Alaçam", "19 Mayıs", "Ayvacık", "Kavak", "Salıpazarı", "Asarcık", "Ladik", "Yakakent"] },
    { id: 56, isim: "Siirt", plaka: "56", ilceler: ["Merkez", "Kurtalan", "Pervari", "Baykan", "Şirvan", "Eruh", "Tillo"] },
    { id: 57, isim: "Sinop", plaka: "57", ilceler: ["Merkez", "Boyabat", "Gerze", "Ayancık", "Durağan", "Türkeli", "Erfelek", "Dikmen", "Saraydüzü"] },
    { id: 58, isim: "Sivas", plaka: "58", ilceler: ["Merkez", "Şarkışla", "Yıldızeli", "Suşehri", "Gemerek", "Zara", "Kangal", "Gürün", "Divriği", "Koyulhisar", "Hafik", "Ulaş", "Altınyayla", "İmranlı", "Akıncılar", "Gölova", "Doğanşar"] },
    { id: 59, isim: "Tekirdağ", plaka: "59", ilceler: ["Çorlu", "Süleymanpaşa", "Çerkezköy", "Kapaklı", "Ergene", "Malkara", "Saray", "Hayrabolu", "Şarköy", "Muratlı", "Marmaraereğlisi"] },
    { id: 60, isim: "Tokat", plaka: "60", ilceler: ["Merkez", "Erbaa", "Turhal", "Niksar", "Zile", "Reşadiye", "Almus", "Pazar", "Yeşilyurt", "Artova", "Sulusaray", "Başçiftlik"] },
    { id: 61, isim: "Trabzon", plaka: "61", ilceler: ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin", "Vakfıkebir", "Sürmene", "Maçka", "Beşikdüzü", "Çarşıbaşı", "Tonya", "Düzköy", "Şalpazarı", "Hayrat", "Köprübaşı", "Çaykara", "Dernekpazarı"] },
    { id: 62, isim: "Tunceli", plaka: "62", ilceler: ["Merkez", "Pertek", "Mazgirt", "Çemişgezek", "Hozat", "Ovacık", "Pülümür", "Nazımiye"] },
    { id: 63, isim: "Şanlıurfa", plaka: "63", ilceler: ["Eyyübiye", "Haliliye", "Siverek", "Viranşehir", "Karaköprü", "Akçakale", "Suruç", "Harran", "Birecik", "Ceylanpınar", "Bozova", "Hilvan", "Halfeti"] },
    { id: 64, isim: "Uşak", plaka: "64", ilceler: ["Merkez", "Banaz", "Eşme", "Sivaslı", "Ulubey", "Karahallı"] },
    { id: 65, isim: "Van", plaka: "65", ilceler: ["İpekyolu", "Erciş", "Tuşba", "Edremit", "Özalp", "Çaldıran", "Başkale", "Muradiye", "Gürpınar", "Gevaş", "Saray", "Çatak", "Bahçesaray"] },
    { id: 66, isim: "Yozgat", plaka: "66", ilceler: ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan", "Sarıkaya", "Çekerek", "Şefaatli", "Saraykent", "Çayıralan", "Kadışehri", "Aydıncık", "Yenifakılı", "Çandır"] },
    { id: 67, isim: "Zonguldak", plaka: "67", ilceler: ["Ereğli", "Merkez", "Çaycuma", "Devrek", "Kozlu", "Alaplı", "Kilimli", "Gökçebey"] },
    { id: 68, isim: "Aksaray", plaka: "68", ilceler: ["Merkez", "Ortaköy", "Eskil", "Gülağaç", "Güzelyurt", "Ağaçören", "Sarıyahşi", "Sultanhanı"] },
    { id: 69, isim: "Bayburt", plaka: "69", ilceler: ["Merkez", "Demirözü", "Aydıntepe"] },
    { id: 70, isim: "Karaman", plaka: "70", ilceler: ["Merkez", "Ermenek", "Sarıveliler", "Ayrancı", "Kazımkarabekir", "Başyayla"] },
    { id: 71, isim: "Kırıkkale", plaka: "71", ilceler: ["Merkez", "Yahşihan", "Keskin", "Delice", "Bahşılı", "Sulakyurt", "Balışeyh", "Karakeçili", "Çelebi"] },
    { id: 72, isim: "Batman", plaka: "72", ilceler: ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"] },
    { id: 73, isim: "Şırnak", plaka: "73", ilceler: ["Cizre", "Silopi", "Merkez", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"] },
    { id: 74, isim: "Bartın", plaka: "74", ilceler: ["Merkez", "Ulus", "Amasra", "Kurucaşile"] },
    { id: 75, isim: "Ardahan", plaka: "75", ilceler: ["Merkez", "Göle", "Çıldır", "Hanak", "Posof", "Damal"] },
    { id: 76, isim: "Iğdır", plaka: "76", ilceler: ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"] },
    { id: 77, isim: "Yalova", plaka: "77", ilceler: ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova", "Armutlu", "Termal"] },
    { id: 78, isim: "Karabük", plaka: "78", ilceler: ["Merkez", "Safranbolu", "Yenice", "Eskipazar", "Eflani", "Ovacık"] },
    { id: 79, isim: "Kilis", plaka: "79", ilceler: ["Merkez", "Musabeyli", "Elbeyli", "Polateli"] },
    { id: 80, isim: "Osmaniye", plaka: "80", ilceler: ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale", "Sumbas", "Hasanbeyli"] },
    { id: 81, isim: "Düzce", plaka: "81", ilceler: ["Merkez", "Akçakoca", "Kaynaşlı", "Gölyaka", "Çilimli", "Yığılca", "Gümüşova", "Cumayeri"] },
    { id: 82, isim: "KKTC", plaka: "KKTC", ilceler: ["Lefkoşa", "Gazimağusa", "Girne", "Güzelyurt", "İskele", "Lefke"] }
];